import 'package:nowa_runtime/nowa_runtime.dart';

@NowaGenerated()
class AppStrings {
  static final Map<String, Map<String, String>> _localizedValues = {
    'Türkçe': {
      'app_title': 'CRAZY BLOCK ONLINE',
      'player': 'Oyuncu',
      'level': 'SEVİYE',
      'high_score': 'EN YÜKSEK SKOR',
      'score_pts': 'PUAN',
      'score': 'SKOR',
      'best': 'En İyi',
      'main_game_mode': 'ANA OYUN MODU',
      'play_classic': 'KLASİK OYNA',
      'play_classic_sub': 'Blokları yerleştir, çizgileri patlat & rekor kır!',
      'online': 'ONLINE',
      'multiplayer': 'Çok Oyunculu',
      'pvp': 'PVP',
      'mini_games': 'MİNİ OYUNLAR',
      'arcade_fun': 'Arcade Eğlence',
      'new_badge': 'YENİ',
      'quick_access': 'HIZLI ERİŞİM',
      'market': 'Mağaza',
      'market_sub': 'Özelleştir',
      'social': 'Sosyal',
      'friends': 'Arkadaş',
      'settings': 'Ayarlar',
      'settings_sub': 'Tercihler',
      'language': 'Dil',
      'coming_soon_online': 'Online Çok Oyunculu Mod Yakında!',
      'coming_soon_mini': 'Mini Oyunlar Çok Yakında!',
      'game': 'Oyun',
      'coins': 'Altın',
      'sound': 'Ses',
      'music': 'Müzik',
      'sfx': 'Ses Efektleri',
      'haptics': 'Titreşim',
      'logout': 'Çıkış Yap',
      'login': 'Giriş Yap',
      'create_account': 'Hesap Oluştur',
      'welcome_back': 'Tekrar Hoş Geldin!',
      'welcome_subtitle': 'Giriş yap ve renkli blokları patlatmaya başla!',
      'email': 'E-posta veya Telefon',
      'password': 'Şifre',
      'confirm_password': 'Şifre Tekrar',
      'username': 'Kullanıcı Adı',
      'forgot_password': 'Şifremi Unuttum?',
      'or_continue_with': 'VEYA ŞUNUNLA DEVAM ET',
      'continue_google': 'Google ile Giriş Yap',
      'continue_guest': 'Misafir Olarak Oyna',
      'no_account': 'Hesabın yok mu? ',
      'have_account': 'Zaten hesabın var mı? ',
      'agree_terms':
          'Kullanım Koşulları ve Gizlilik Politikasını kabul ediyorum',
      'terms_of_service': 'Kullanım Koşulları',
      'privacy_policy': 'Gizlilik Politikası',
      'enter_username': 'Lütfen kullanıcı adı girin',
      'enter_email': 'Lütfen e-posta girin',
      'enter_password': 'Lütfen şifre girin',
      'passwords_mismatch': 'Şifreler eşleşmiyor',
      'min_password_len': 'Şifre en az 6 karakter olmalı',
      'min_username_len': 'Kullanıcı adı en az 3 karakter olmalı',
      'pause': 'Duraklat',
      'paused': 'OYUN DURAKLATILDI',
      'resume': 'DEVAM ET',
      'restart': 'YENİDEN BAŞLAT',
      'quit': 'ÇIKIŞ',
      'main_menu': 'ANA MENÜ',
      'game_over': 'OYUN BİTTİ',
      'new_record': 'YENİ REKOR!',
      'great_job': 'Harika İş Çıkardın!',
      'final_score': 'Toplam Skor',
      'coins_earned': 'Kazanılan Altın',
      'next_pieces': 'GELECEK BLOKLAR',
      'select_piece_hint': 'Bir blok seç ve tahtaya dokunarak yerleştir!',
      'game_board_hint':
          'Blokları tahtaya yerleştir, satır ve sütunları doldurarak patlat!',
      'blocks_tab': 'BLOKLAR',
      'backgrounds_tab': 'ARKA PLANLAR',
      'effects_tab': 'EFEKTLER',
      'rarity_common': 'YAYGIN',
      'rarity_rare': 'NADİR',
      'rarity_epic': 'EPİK',
      'rarity_legendary': 'EFSANEVİ',
      'equipped': 'KUŞANILDI',
      'equip': 'KUŞAN',
      'buy': 'SATIN AL',
      'unlocked': 'AÇILDI',
      'not_enough_coins': 'Yetersiz Altın!',
      'item_equipped': 'Öğe başarıyla kuşandı!',
      'item_purchased': 'Öğe satın alındı ve kuşandı!',
      'get_coins': 'Altın Al & Kazan',
      'buy_coins': 'Altın Paketleri',
      'watch_ad_coins': 'Reklam İzle & 50 Altın Kazan',
      'ad_watched_reward': 'Tebrikler! +50 Altın hesabına eklendi.',
      'my_friends': 'ARKADAŞLARIM',
      'find_friends': 'ARKADAŞ BUL',
      'invitations': 'DAVETLER',
      'no_friends_yet': 'Henüz Arkadaşın Yok',
      'find_friends_hint': 'Arkadaş eklemek için oyuncu ID ile arama yap!',
      'no_invitations': 'Bekleyen Davet Yok',
      'no_invitations_hint': 'Şu anda gelen bir arkadaşlık isteği bulunmuyor.',
      'invite': 'DAVET ET',
      'accept': 'KABUL ET',
      'decline': 'REDDET',
      'search_player_hint': 'Oyuncu ID veya İsim Gir (örn: #CBO-58291)...',
      'search': 'ARA',
      'friend_invited': 'oyuna davet edildi!',
      'friend_added': 'arkadaş listene eklendi!',
      'copy_id': 'ID KOPYALA',
      'id_copied': 'Oyuncu ID panoya kopyalandı!',
      'account': 'Hesap',
      'profile': 'PROFİL',
      'career_stats': 'KARİYER İSTATİSTİKLERİ',
      'edit_profile': 'Profili Düzenle',
      'verified': 'Doğrulanmış',
      'unverified': 'Doğrulanmamış',
      'security': 'GÜVENLİK',
      'change_password': 'Şifre Değiştir',
      'danger_zone': 'TEHLİKELİ BÖLGE',
      'delete_account': 'HESABI SİL',
      'delete_account_confirm':
          'Hesabınızı silmek istediğinize emin misiniz? Bu işlem geri alınamaz.',
      'cancel': 'İptal',
      'confirm': 'Onayla',
      'delete': 'Sil',
      'about': 'Hakkında',
      'about_game': 'OYUN HAKKINDA',
      'game_description':
          'Crazy Block Online, renkli ve eğlenceli blok bulmaca dinamiklerini modern arayüz, zengin özelleştirme ve rekabetçi lig sistemiyle birleştiren profesyonel bir mobil bulmaca oyunudur.',
      'features': 'Özellikler',
      'credits': 'YAPIMCILAR & EMEĞİ GEÇENLER',
      'made_by': 'Geliştirici: Zodiac',
      'made_with_love':
          'Flutter teknolojisi ve bulmaca oyunu tutkusuyla üretildi.',
      'version': 'Sürüm 0.9',
      'website': 'Web Sitesi',
      'support': 'Destek',
      'save': 'KAYDET',
      'league': 'LİG',
      'league_bronze': 'Bronz Ligi',
      'league_silver': 'Gümüş Ligi',
      'league_gold': 'Altın Ligi',
      'league_diamond': 'Elmas Ligi',
      'league_world': 'Dünya Ligi',
      'league_standings': 'LİG SIRALAMASI',
      'rank': 'Sıra',
      'leaderboard': 'Liderlik Tablosu',
      'top_players': 'En İyiler',
      'audio_settings': 'SES & EFEKTLER',
      'preferences_system': 'TERCİHLER & SİSTEM',
    },
    'English': {
      'app_title': 'CRAZY BLOCK ONLINE',
      'player': 'Player',
      'level': 'LEVEL',
      'high_score': 'HIGH SCORE',
      'score_pts': 'PTS',
      'score': 'SCORE',
      'best': 'Best',
      'main_game_mode': 'MAIN GAME MODE',
      'play_classic': 'PLAY CLASSIC',
      'play_classic_sub': 'Place blocks, blast lines & beat high scores!',
      'online': 'ONLINE',
      'multiplayer': 'Multiplayer',
      'pvp': 'PVP',
      'mini_games': 'MINI GAMES',
      'arcade_fun': 'Arcade Fun',
      'new_badge': 'NEW',
      'quick_access': 'QUICK ACCESS',
      'market': 'Market',
      'market_sub': 'Customize',
      'social': 'Social',
      'friends': 'Friends',
      'settings': 'Settings',
      'settings_sub': 'Preferences',
      'language': 'Language',
      'coming_soon_online': 'Online Multiplayer Coming Soon!',
      'coming_soon_mini': 'Mini Games Coming Soon!',
      'game': 'Game',
      'coins': 'Coins',
      'sound': 'Sound',
      'music': 'Music',
      'sfx': 'Sound Effects',
      'haptics': 'Haptics',
      'logout': 'Log Out',
      'login': 'Log In',
      'create_account': 'Create Account',
      'welcome_back': 'Welcome Back!',
      'welcome_subtitle': 'Sign in and blast colorful block lines!',
      'email': 'Email or Phone',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'username': 'Username',
      'forgot_password': 'Forgot Password?',
      'or_continue_with': 'OR CONTINUE WITH',
      'continue_google': 'Continue with Google',
      'continue_guest': 'Play as Guest',
      'no_account': 'Don\'t have an account? ',
      'have_account': 'Already have an account? ',
      'agree_terms': 'I agree to the Terms of Service and Privacy Policy',
      'terms_of_service': 'Terms of Service',
      'privacy_policy': 'Privacy Policy',
      'enter_username': 'Please enter username',
      'enter_email': 'Please enter email',
      'enter_password': 'Please enter password',
      'passwords_mismatch': 'Passwords do not match',
      'min_password_len': 'Password must be at least 6 characters',
      'min_username_len': 'Username must be at least 3 characters',
      'pause': 'Pause',
      'paused': 'GAME PAUSED',
      'resume': 'RESUME',
      'restart': 'RESTART',
      'quit': 'QUIT',
      'main_menu': 'MAIN MENU',
      'game_over': 'GAME OVER',
      'new_record': 'NEW RECORD!',
      'great_job': 'Great Job!',
      'final_score': 'Final Score',
      'coins_earned': 'Coins Earned',
      'next_pieces': 'NEXT PIECES',
      'select_piece_hint': 'Select a block below, then tap grid to place!',
      'game_board_hint':
          'Drag or tap blocks onto the board, fill rows and columns to blast them!',
      'blocks_tab': 'BLOCKS',
      'backgrounds_tab': 'BACKGROUNDS',
      'effects_tab': 'EFFECTS',
      'rarity_common': 'COMMON',
      'rarity_rare': 'RARE',
      'rarity_epic': 'EPIC',
      'rarity_legendary': 'LEGENDARY',
      'equipped': 'EQUIPPED',
      'equip': 'EQUIP',
      'buy': 'BUY',
      'unlocked': 'UNLOCKED',
      'not_enough_coins': 'Not enough coins!',
      'item_equipped': 'Item equipped successfully!',
      'item_purchased': 'Item purchased and equipped!',
      'get_coins': 'Get & Earn Coins',
      'buy_coins': 'Coin Packages',
      'watch_ad_coins': 'Watch Ad & Earn 50 Coins',
      'ad_watched_reward': 'Congratulations! +50 Coins added to your balance.',
      'my_friends': 'MY FRIENDS',
      'find_friends': 'FIND FRIENDS',
      'invitations': 'INVITATIONS',
      'no_friends_yet': 'No Friends Yet',
      'find_friends_hint': 'Search with player ID to find friends!',
      'no_invitations': 'No Invitations',
      'no_invitations_hint': 'You have no pending friend requests right now.',
      'invite': 'INVITE',
      'accept': 'ACCEPT',
      'decline': 'DECLINE',
      'search_player_hint': 'Enter Player ID or Name (e.g. #CBO-58291)...',
      'search': 'SEARCH',
      'friend_invited': 'invited to play!',
      'friend_added': 'added to friends list!',
      'copy_id': 'COPY ID',
      'id_copied': 'Player ID copied to clipboard!',
      'account': 'Account',
      'profile': 'PROFILE',
      'career_stats': 'CAREER STATS',
      'edit_profile': 'Edit Profile',
      'verified': 'Verified',
      'unverified': 'Unverified',
      'security': 'SECURITY',
      'change_password': 'Change Password',
      'danger_zone': 'DANGER ZONE',
      'delete_account': 'DELETE ACCOUNT',
      'delete_account_confirm':
          'Are you sure you want to delete your account? This action cannot be undone.',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'delete': 'Delete',
      'about': 'About',
      'about_game': 'ABOUT THE GAME',
      'game_description':
          'Crazy Block Online is a colorful, friendly mobile puzzle game featuring classic block placement, line blasts, rich customization, and ranking leagues.',
      'features': 'Features',
      'credits': 'CREDITS & STUDIO',
      'made_by': 'Developed by Zodiac',
      'made_with_love': 'Built with Flutter and passion for puzzle gameplay.',
      'version': 'Version 0.9',
      'website': 'Website',
      'support': 'Support',
      'save': 'SAVE',
      'league': 'LEAGUE',
      'league_bronze': 'Bronze League',
      'league_silver': 'Silver League',
      'league_gold': 'Gold League',
      'league_diamond': 'Diamond League',
      'league_world': 'World League',
      'league_standings': 'LEAGUE STANDINGS',
      'rank': 'Rank',
      'leaderboard': 'Leaderboard',
      'top_players': 'Top Players',
      'audio_settings': 'AUDIO & SFX',
      'preferences_system': 'PREFERENCES & SYSTEM',
    },
    'Deutsch': {
      'app_title': 'CRAZY BLOCK ONLINE',
      'player': 'Spieler',
      'level': 'STUFE',
      'high_score': 'REKORD',
      'score_pts': 'PKT',
      'score': 'PUNKTE',
      'best': 'Beste',
      'main_game_mode': 'HAUPTSPIELMODUS',
      'play_classic': 'KLASSISCH SPIELEN',
      'play_classic_sub': 'Blöcke platzieren und Linien löschen!',
      'online': 'ONLINE',
      'multiplayer': 'Mehrspieler',
      'pvp': 'PVP',
      'mini_games': 'MINISPIELE',
      'arcade_fun': 'Arcade-Spaß',
      'new_badge': 'NEU',
      'quick_access': 'SCHNELLZUGRIFF',
      'market': 'Markt',
      'market_sub': 'Anpassen',
      'social': 'Sozial',
      'friends': 'Freunde',
      'settings': 'Einstellungen',
      'settings_sub': 'Präferenzen',
      'language': 'Sprache',
      'coming_soon_online': 'Online-Mehrspielermodus kommt bald!',
      'coming_soon_mini': 'Minispiele kommen bald!',
      'game': 'Spiel',
      'coins': 'Münzen',
      'sound': 'Ton',
      'music': 'Musik',
      'sfx': 'Soundeffekte',
      'haptics': 'Haptik',
      'logout': 'Abmelden',
      'login': 'Anmelden',
      'create_account': 'Konto erstellen',
      'welcome_back': 'Willkommen zurück!',
      'welcome_subtitle': 'Melde dich an und starte das Puzzle-Abenteuer!',
      'email': 'E-Mail oder Telefon',
      'password': 'Passwort',
      'confirm_password': 'Passwort bestätigen',
      'username': 'Benutzername',
      'forgot_password': 'Passwort vergessen?',
      'or_continue_with': 'ODER WEITER MIT',
      'continue_google': 'Mit Google fortfahren',
      'continue_guest': 'Als Gast spielen',
      'no_account': 'Noch kein Konto? ',
      'have_account': 'Bereits ein Konto? ',
      'agree_terms':
          'Ich stimme den Nutzungsbedingungen und Datenschutzbestimmungen zu',
      'terms_of_service': 'Nutzungsbedingungen',
      'privacy_policy': 'Datenschutzrichtlinie',
      'enter_username': 'Bitte Benutzernamen eingeben',
      'enter_email': 'Bitte E-Mail eingeben',
      'enter_password': 'Bitte Passwort eingeben',
      'passwords_mismatch': 'Passwörter stimmen nicht überein',
      'min_password_len': 'Passwort muss mind. 6 Zeichen lang sein',
      'min_username_len': 'Benutzername muss mind. 3 Zeichen lang sein',
      'pause': 'Pause',
      'paused': 'SPIEL PAUSIERT',
      'resume': 'WEITERSPIELEN',
      'restart': 'NEUSTART',
      'quit': 'BEENDEN',
      'main_menu': 'HAUPTMENÜ',
      'game_over': 'SPIEL VORBEI',
      'new_record': 'NEUER REKORD!',
      'great_job': 'Tolle Leistung!',
      'final_score': 'Endstand',
      'coins_earned': 'Verdiente Münzen',
      'next_pieces': 'NÄCHSTE BLÖCKE',
      'select_piece_hint': 'Block auswählen und auf das Spielfeld tippen!',
      'game_board_hint': 'Ziehe Blöcke auf das Spielfeld und lösche Reihen!',
      'blocks_tab': 'BLÖCKE',
      'backgrounds_tab': 'HINTERGRÜNDE',
      'effects_tab': 'EFFEKTE',
      'rarity_common': 'GEWÖHNLICH',
      'rarity_rare': 'SELTEN',
      'rarity_epic': 'EPISCH',
      'rarity_legendary': 'LEGENDÄR',
      'equipped': 'AUSGERÜSTET',
      'equip': 'AUSRÜSTEN',
      'buy': 'KAUFEN',
      'unlocked': 'FREIGESCHALTET',
      'not_enough_coins': 'Nicht genügend Münzen!',
      'item_equipped': 'Gegenstand erfolgreich ausgerüstet!',
      'item_purchased': 'Gegenstand gekauft und ausgerüstet!',
      'get_coins': 'Münzen erhalten',
      'buy_coins': 'Münzpakete',
      'watch_ad_coins': 'Werbung ansehen & 50 Münzen erhalten',
      'ad_watched_reward': 'Glückwunsch! +50 Münzen gutgeschrieben.',
      'my_friends': 'MEINE FREUNDE',
      'find_friends': 'FREUNDE FINDEN',
      'invitations': 'EINLADUNGEN',
      'no_friends_yet': 'Noch keine Freunde',
      'find_friends_hint': 'Finde neue Freunde mit Spieler-ID!',
      'no_invitations': 'Keine Einladungen',
      'no_invitations_hint': 'Du hast zurzeit keine ausstehenden Anfragen.',
      'invite': 'EINLADEN',
      'accept': 'ANNEHMEN',
      'decline': 'ABLEHNEN',
      'search_player_hint': 'Spieler-ID oder Name eingeben...',
      'search': 'SUCHEN',
      'friend_invited': 'zum Spiel eingeladen!',
      'friend_added': 'als Freund hinzugefügt!',
      'copy_id': 'ID KOPIEREN',
      'id_copied': 'Spieler-ID kopiert!',
      'account': 'Konto',
      'profile': 'PROFIL',
      'career_stats': 'KARRIERE-STATISTIK',
      'edit_profile': 'Profil bearbeiten',
      'verified': 'Verifiziert',
      'unverified': 'Nicht verifiziert',
      'security': 'SICHERHEIT',
      'change_password': 'Passwort ändern',
      'danger_zone': 'GEFAHRENZONE',
      'delete_account': 'KONTO LÖSCHEN',
      'delete_account_confirm': 'Möchtest du dein Konto wirklich löschen?',
      'cancel': 'Abbrechen',
      'confirm': 'Bestätigen',
      'delete': 'Löschen',
      'about': 'Über das Spiel',
      'about_game': 'ÜBER DAS SPIEL',
      'game_description':
          'Crazy Block Online ist ein buntes Block-Puzzle-Spiel mit modernem Design und Liga-Ranglisten.',
      'features': 'Funktionen',
      'credits': 'MITWIRKENDE',
      'made_by': 'Entwickelt von Zodiac',
      'made_with_love': 'Entwickelt mit Flutter & Leidenschaft.',
      'version': 'Version 0.9',
      'website': 'Webseite',
      'support': 'Support',
      'save': 'SPEICHERN',
      'league': 'LIGA',
      'league_bronze': 'Bronze-Liga',
      'league_silver': 'Silber-Liga',
      'league_gold': 'Gold-Liga',
      'league_diamond': 'Diamant-Liga',
      'league_world': 'Welt-Liga',
      'league_standings': 'LIGA-TABELLE',
      'rank': 'Rang',
      'leaderboard': 'Rangliste',
      'top_players': 'Top-Spieler',
      'audio_settings': 'AUDIO & EFFEKTE',
      'preferences_system': 'EINSTELLUNGEN & SYSTEM',
    },
    'Español': {
      'app_title': 'CRAZY BLOCK ONLINE',
      'player': 'Jugador',
      'level': 'NIVEL',
      'high_score': 'RÉCORD',
      'score_pts': 'PTS',
      'score': 'PUNTOS',
      'best': 'Mejor',
      'main_game_mode': 'MODO PRINCIPAL',
      'play_classic': 'JUGAR CLÁSICO',
      'play_classic_sub': '¡Coloca bloques y destruye líneas!',
      'online': 'EN LÍNEA',
      'multiplayer': 'Multijugador',
      'pvp': 'PVP',
      'mini_games': 'MINIJUEGOS',
      'arcade_fun': 'Diversión Arcade',
      'new_badge': 'NUEVO',
      'quick_access': 'ACCESO RÁPIDO',
      'market': 'Tienda',
      'market_sub': 'Personalizar',
      'social': 'Social',
      'friends': 'Amigos',
      'settings': 'Ajustes',
      'settings_sub': 'Preferencias',
      'language': 'Idioma',
      'coming_soon_online': '¡Multijugador online próximamente!',
      'coming_soon_mini': '¡Minijuegos próximamente!',
      'game': 'Juego',
      'coins': 'Monedas',
      'sound': 'Sonido',
      'music': 'Música',
      'sfx': 'Efectos de Sonido',
      'haptics': 'Vibración',
      'logout': 'Cerrar sesión',
      'login': 'Iniciar Sesión',
      'create_account': 'Crear Cuenta',
      'welcome_back': '¡Bienvenido de nuevo!',
      'welcome_subtitle': '¡Inicia sesión y empieza a romper bloques!',
      'email': 'Correo o Teléfono',
      'password': 'Contraseña',
      'confirm_password': 'Confirmar Contraseña',
      'username': 'Nombre de Usuario',
      'forgot_password': '¿Olvidaste tu contraseña?',
      'or_continue_with': 'O CONTINUAR CON',
      'continue_google': 'Continuar con Google',
      'continue_guest': 'Jugar como Invitado',
      'no_account': '¿No tienes cuenta? ',
      'have_account': '¿Ya tienes una cuenta? ',
      'agree_terms':
          'Acepto los Términos de Servicio y la Política de Privacidad',
      'terms_of_service': 'Términos de Servicio',
      'privacy_policy': 'Política de Privacidad',
      'enter_username': 'Por favor ingresa un usuario',
      'enter_email': 'Por favor ingresa un correo',
      'enter_password': 'Por favor ingresa una contraseña',
      'passwords_mismatch': 'Las contraseñas no coinciden',
      'min_password_len': 'La contraseña debe tener al menos 6 caracteres',
      'min_username_len': 'El usuario debe tener al menos 3 caracteres',
      'pause': 'Pausa',
      'paused': 'JUEGO EN PAUSA',
      'resume': 'REANUDAR',
      'restart': 'REINICIAR',
      'quit': 'SALIR',
      'main_menu': 'MENÚ PRINCIPAL',
      'game_over': 'FIN DEL JUEGO',
      'new_record': '¡NUEVO RÉCORD!',
      'great_job': '¡Gran Trabajo!',
      'final_score': 'Puntuación Final',
      'coins_earned': 'Monedas Ganadas',
      'next_pieces': 'SIGUIENTES BLOQUES',
      'select_piece_hint': '¡Selecciona un bloque y toca el tablero!',
      'game_board_hint': '¡Arrastra bloques al tablero y completa líneas!',
      'blocks_tab': 'BLOQUES',
      'backgrounds_tab': 'FONDOS',
      'effects_tab': 'EFECTOS',
      'rarity_common': 'COMÚN',
      'rarity_rare': 'RARO',
      'rarity_epic': 'ÉPICO',
      'rarity_legendary': 'LEGENDARIO',
      'equipped': 'EQUIPADO',
      'equip': 'EQUIPAR',
      'buy': 'COMPRAR',
      'unlocked': 'DESBLOQUEADO',
      'not_enough_coins': '¡Monedas insuficientes!',
      'item_equipped': '¡Objeto equipado correctamente!',
      'item_purchased': '¡Objeto comprado y equipado!',
      'get_coins': 'Obtener Monedas',
      'buy_coins': 'Paquetes de Monedas',
      'watch_ad_coins': 'Ver Anuncio & Ganar 50 Monedas',
      'ad_watched_reward': '¡Felicidades! +50 monedas agregadas.',
      'my_friends': 'MIS AMIGOS',
      'find_friends': 'BUSCAR AMIGOS',
      'invitations': 'SOLICITUDES',
      'no_friends_yet': 'Aún no tienes amigos',
      'find_friends_hint': '¡Usa el ID de jugador para encontrar amigos!',
      'no_invitations': 'Sin Solicitudes',
      'no_invitations_hint':
          'No tienes solicitudes pendientes en este momento.',
      'invite': 'INVITAR',
      'accept': 'ACEPTAR',
      'decline': 'RECHAZAR',
      'search_player_hint': 'Ingresa ID o nombre...',
      'search': 'BUSCAR',
      'friend_invited': '¡invitado a la partida!',
      'friend_added': '¡agregado como amigo!',
      'copy_id': 'COPIAR ID',
      'id_copied': '¡ID copiado al portapapeles!',
      'account': 'Cuenta',
      'profile': 'PERFIL',
      'career_stats': 'ESTADÍSTICAS',
      'edit_profile': 'Editar Perfil',
      'verified': 'Verificado',
      'unverified': 'No verificado',
      'security': 'SEGURIDAD',
      'change_password': 'Cambiar Contraseña',
      'danger_zone': 'ZONA DE PELIGRO',
      'delete_account': 'ELIMINAR CUENTA',
      'delete_account_confirm': '¿Estás seguro de eliminar tu cuenta?',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'delete': 'Eliminar',
      'about': 'Acerca de',
      'about_game': 'SOBRE EL JUEGO',
      'game_description':
          'Crazy Block Online es un divertido juego de rompecabezas de bloques con ligas competitivas y personalización.',
      'features': 'Características',
      'credits': 'CRÉDITOS',
      'made_by': 'Creado por Zodiac',
      'made_with_love': 'Hecho con Flutter y mucha pasión.',
      'version': 'Versión 0.9',
      'website': 'Sitio Web',
      'support': 'Soporte',
      'save': 'GUARDAR',
      'league': 'LIGA',
      'league_bronze': 'Liga Bronce',
      'league_silver': 'Liga Plata',
      'league_gold': 'Liga Oro',
      'league_diamond': 'Liga Diamante',
      'league_world': 'Liga Mundial',
      'league_standings': 'POSICIONES DE LIGA',
      'rank': 'Puesto',
      'leaderboard': 'Clasificación',
      'top_players': 'Mejores Jugadores',
      'audio_settings': 'AUDIO & EFECTOS',
      'preferences_system': 'PREFERENCIAS & SISTEMA',
    },
    'Français': {
      'app_title': 'CRAZY BLOCK ONLINE',
      'player': 'Joueur',
      'level': 'NIVEAU',
      'high_score': 'MEILLEUR SCORE',
      'score_pts': 'PTS',
      'score': 'SCORE',
      'best': 'Top',
      'main_game_mode': 'MODE PRINCIPAL',
      'play_classic': 'JOUER CLASSIQUE',
      'play_classic_sub': 'Placez les blocs et battez le record !',
      'online': 'EN LIGNE',
      'multiplayer': 'Multijoueur',
      'pvp': 'PVP',
      'mini_games': 'MINI-JEUX',
      'arcade_fun': 'Fun Arcade',
      'new_badge': 'NOUVEAU',
      'quick_access': 'ACCÈS RAPIDE',
      'market': 'Boutique',
      'market_sub': 'Personnaliser',
      'social': 'Social',
      'friends': 'Amis',
      'settings': 'Paramètres',
      'settings_sub': 'Préférences',
      'language': 'Langue',
      'coming_soon_online': 'Multijoueur en ligne bientôt disponible !',
      'coming_soon_mini': 'Mini-jeux bientôt disponibles !',
      'game': 'Jeu',
      'coins': 'Pièces',
      'sound': 'Son',
      'music': 'Musique',
      'sfx': 'Effets Sonores',
      'haptics': 'Vibrations',
      'logout': 'Déconnexion',
      'login': 'Connexion',
      'create_account': 'Créer un Compte',
      'welcome_back': 'Bon retour !',
      'welcome_subtitle': 'Connectez-vous et explosez les records !',
      'email': 'Email ou Téléphone',
      'password': 'Mot de passe',
      'confirm_password': 'Confirmer mot de passe',
      'username': 'Nom d\'utilisateur',
      'forgot_password': 'Mot de passe oublié ?',
      'or_continue_with': 'OU CONTINUER AVEC',
      'continue_google': 'Continuer avec Google',
      'continue_guest': 'Jouer en Invité',
      'no_account': 'Pas de compte ? ',
      'have_account': 'Déjà un compte ? ',
      'agree_terms':
          'J\'accepte les Conditions d\'utilisation et la Politique de confidentialité',
      'terms_of_service': 'Conditions d\'utilisation',
      'privacy_policy': 'Politique de confidentialité',
      'enter_username': 'Veuillez entrer un nom d\'utilisateur',
      'enter_email': 'Veuillez entrer un email',
      'enter_password': 'Veuillez entrer un mot de passe',
      'passwords_mismatch': 'Les mots de passe ne correspondent pas',
      'min_password_len': 'Le mot de passe doit contenir au moins 6 caractères',
      'min_username_len':
          'Le nom d\'utilisateur doit contenir au moins 3 caractères',
      'pause': 'Pause',
      'paused': 'JEU EN PAUSE',
      'resume': 'REPRENDRE',
      'restart': 'RECOMMENCER',
      'quit': 'QUITTER',
      'main_menu': 'MENU PRINCIPAL',
      'game_over': 'PARTIE TERMINÉE',
      'new_record': 'NOUVEAU RECORD !',
      'great_job': 'Superbe Partie !',
      'final_score': 'Score Final',
      'coins_earned': 'Pièces Gagnées',
      'next_pieces': 'PROCHAINS BLOCS',
      'select_piece_hint': 'Sélectionnez un bloc puis touchez la grille !',
      'game_board_hint':
          'Glissez les blocs sur le plateau pour détruire des lignes !',
      'blocks_tab': 'BLOCS',
      'backgrounds_tab': 'ARRIÈRE-PLANS',
      'effects_tab': 'EFFETS',
      'rarity_common': 'COMMUN',
      'rarity_rare': 'RARE',
      'rarity_epic': 'ÉPIQUE',
      'rarity_legendary': 'LÉGENDAIRE',
      'equipped': 'ÉQUIPÉ',
      'equip': 'ÉQUIPER',
      'buy': 'ACHETER',
      'unlocked': 'DÉBLOQUÉ',
      'not_enough_coins': 'Pas assez de pièces !',
      'item_equipped': 'Objet équipé avec succès !',
      'item_purchased': 'Objet acheté et équipé !',
      'get_coins': 'Obtenir des pièces',
      'buy_coins': 'Packs de pièces',
      'watch_ad_coins': 'Regarder une pub & Gagner 50 pièces',
      'ad_watched_reward': 'Félicitations ! +50 pièces ajoutées.',
      'my_friends': 'MES AMIS',
      'find_friends': 'TROUVER DES AMIS',
      'invitations': 'INVITATIONS',
      'no_friends_yet': 'Pas encore d\'amis',
      'find_friends_hint': 'Cherchez par ID de joueur pour trouver des amis !',
      'no_invitations': 'Aucune Invitation',
      'no_invitations_hint': 'Vous n\'avez aucune demande en attente.',
      'invite': 'INVITER',
      'accept': 'ACCEPTER',
      'decline': 'REFUSER',
      'search_player_hint': 'Entrez ID ou nom...',
      'search': 'CHERCHER',
      'friend_invited': 'invité à jouer !',
      'friend_added': 'ajouté aux amis !',
      'copy_id': 'COPIER ID',
      'id_copied': 'ID copié dans le presse-papiers !',
      'account': 'Compte',
      'profile': 'PROFIL',
      'career_stats': 'STATISTIQUES DE CARRIÈRE',
      'edit_profile': 'Modifier le profil',
      'verified': 'Vérifié',
      'unverified': 'Non vérifié',
      'security': 'SÉCURITÉ',
      'change_password': 'Changer mot de passe',
      'danger_zone': 'ZONE DANGER',
      'delete_account': 'SUPPRIMER LE COMPTE',
      'delete_account_confirm':
          'Êtes-vous sûr de vouloir supprimer votre compte ?',
      'cancel': 'Annuler',
      'confirm': 'Confirmer',
      'delete': 'Supprimer',
      'about': 'À propos',
      'about_game': 'À PROPOS DU JEU',
      'game_description':
          'Crazy Block Online est un jeu de puzzle de blocs captivant avec des ligues compétitives et de la personnalisation.',
      'features': 'Fonctionnalités',
      'credits': 'CRÉDITS',
      'made_by': 'Développé par Zodiac',
      'made_with_love': 'Créé avec Flutter et passion.',
      'version': 'Version 0.9',
      'website': 'Site Web',
      'support': 'Support',
      'save': 'ENREGISTRER',
      'league': 'LIGUE',
      'league_bronze': 'Ligue Bronze',
      'league_silver': 'Ligue Argent',
      'league_gold': 'Ligue Or',
      'league_diamond': 'Ligue Diamant',
      'league_world': 'Ligue Mondiale',
      'league_standings': 'CLASSEMENT DE LIGUE',
      'rank': 'Rang',
      'leaderboard': 'Classement',
      'top_players': 'Meilleurs Joueurs',
      'audio_settings': 'AUDIO & EFFETS',
      'preferences_system': 'PRÉFÉRENCES & SYSTÈME',
    },
  };

  static String tr(String key, String language) {
    final langDict = _localizedValues[language] ?? _localizedValues['Türkçe'];
    return langDict?[key] ??
        _localizedValues['Türkçe']?[key] ??
        _localizedValues['English']?[key] ??
        key;
  }
}
